feat(core,paas-ws-provider): onbaording prerequiste - move to spring-boot 1.3-M5
 Switch to spring-boot 1.3-M5.
   - upgrade cxf (new version: 3.1.2) to fix NoSuchMethodError: org.springframework.aop.support.AopUtils.isCglibProxyClass
   - move activemq (new version: 5.12.0) to fix org.apache.activemq.jms.pool.PooledConnectionFactory.setConnectionFactory